services:
  app:
    build: .
    container_name: tribute_app
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tribute_network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: tribute_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: tribute_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tribute_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tribute_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - tribute_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  tribute_network:
    driver: bridge 