services:
  app:
    build: .
    container_name: tribute_app
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=tribute_db
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRY=24h
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tribute_network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: tribute_postgres
    environment:
      POSTGRES_DB: tribute_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - tribute_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tribute_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tribute_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    container_name: tribute_migrate
    command: ["-path", "/migrations", "-database", "postgres://postgres:password@postgres:5432/tribute_db?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    networks:
      - tribute_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:

networks:
  tribute_network:
    driver: bridge 