name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH Key Format
      run: |
        echo "Testing SSH key format..."
        echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
        echo "SSH_PRIVATE_KEY starts with: ${SSH_PRIVATE_KEY:0:50}"
        echo "SSH_PRIVATE_KEY ends with: ${SSH_PRIVATE_KEY: -50}"
        
        # Check if it's a valid SSH key format
        if [[ "${{ secrets.SSH_PRIVATE_KEY }}" == *"-----BEGIN"* ]] && [[ "${{ secrets.SSH_PRIVATE_KEY }}" == *"-----END"* ]]; then
          echo "✅ SSH key format looks correct"
        else
          echo "❌ SSH key format appears incorrect"
        fi
        
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          echo "SSH connection successful!"
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "SSH key test passed!"
        port: 22
        timeout: 30s 